"""add created_at to tasks

Revision ID: 65ae5c6b4354
Revises: 
Create Date: 2026-09-21 00:27:17.165204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65ae5c6b4354'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'tasks',
        sa.Column(
            'created_at',
            sa.DateTime(),
            nullable=True
        )
    )

    op.execute(
        "UPDATE tasks SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL"
    )

    with op.batch_alter_table('tasks') as batch_op:
        batch_op.alter_column(
            'created_at',
            existing_type=sa.DateTime(),
            nullable=False
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'created_at')
    # ### end Alembic commands ###
